[package]
name = "credential_service_mock"
version = "0.45.0"
authors = ["Matthew Mayer <matthewkmayer@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["macros"] }
warp = "0.2"
